### PR TITLE
Add snowbot

### PR DESCRIPTION
**Pull request by rivques**
Snowbot is a bot that draws snow art in a similar way to a 3D printer. A much more in-depth summary is available in the README.

It's been a while since I've submitted anything to the botpack, but I *think* I've included the correct files & folders. Please tell me if I'm missing something or need something!

### CODE REVIEW

**Review by VirxEC — CHANGES_REQUESTED** [review]
`_config.yml` is not needed, and I don't think that the tests folder is needed either

**Comment by rivques** [comment]
Oops, I thought I got `config.yml`. I meant `tests` more as a resource for people who just want to see how the bot works and don't want to go to the trouble of installing and configuring Cura, so what if I rename that folder to `examples` instead?

**Comment by VirxEC** [comment]
These files are thousands of lines long each, and the botpack is not for storing development stuff - anyone who may wish into your bot should go to your GitHub page, which is partially what that is for.

We have more other devs delete source code for their C# bots in the past who gave a similar reason

**Comment by rivques** [comment]
Alright, fixed.

**Review by VirxEC — APPROVED** [review]
Thanks, the rest looks good to me - just need to wait for @tarehart

**Review by tarehart — APPROVED** [review]

**Pull request merged**
