### PR TITLE
Adding Noob Blue

### PR DESCRIPTION
**Pull request by rocketeeroof**
This version is directly copy & pasted from the recent RLBot tournament

### CODE REVIEW

**Comment by VirxEC** [comment]
In light of us moving to try and make the botpack smaller, please choose between "Noob Bot" and "Noob Blue" being in the botpack.

**Comment by rocketeeroof** [comment]
In that case I choose Blue.

If I need to do anything now I will.

**Comment by VirxEC** [comment]
Adding a commit removing the old bot might be the easiest

**Comment by rocketeeroof** [comment]
Very well.

**Comment by VirxEC** [comment]
Story Mode also needs to be updated to use the new bot, we can worry about that a little later.

**Review by VirxEC — APPROVED** [review]

**Pull request merged**
