### PR TITLE
Cheesus 3v3 compatibility

### PR DESCRIPTION
**Pull request by JoshyDevRL**

### CODE REVIEW

**Comment by VirxEC** [comment]
Can you please remove the __pycache__ folders? If you're going to include Python in your bot, it must be the source code and not the pyc files.

**Comment by JoshyDevRL** [comment]
My bad i forgot to del them after testing. Should be good

**Comment by VirxEC** [comment]
I also noticed that you added `RLBot_Core_Interface.dll`, I don't think that's needed.

**Comment by VirxEC** [comment]
Have you tested that?

**Comment by JoshyDevRL** [comment]
Let me test rn

**Comment by JoshyDevRL** [comment]
yep it works

**Review by VirxEC — APPROVED** [review]

**Pull request merged**
