### PR TITLE
Add fillamentbot to botpack

### PR DESCRIPTION
**Pull request by jboardman367**
I hope I did this right

### CODE REVIEW

**Comment by VirxEC** [comment]
You only need the code within the src folder for your bot to run. Please remove the other stuff

**Comment by ViliamVadocz** [comment]
I also noticed you have `tmcp.py` in your utils. Are you not using the package?

**Comment by jboardman367** [comment]
It was just in there from the old version, forgot to remove it. Have done so now.

**Comment by VirxEC** [comment]
If you’re using the TMCP package, please specify that as a requirement. Ask in the discord if you’re not entirely sure how to do that.

**Comment by jboardman367** [comment]
It doesn't have TMCP at all, I just removed the unused import at the start of the file. I had it, then removed it when I did a re-write but forgot to take out the module. Should be good now.

**Review by VirxEC — APPROVED** [review]
Looks great!!! I’m super excited to have another bot in the botpack!

**Pull request merged**
