### PR TITLE
Adding Sinc to botpack

### PR DESCRIPTION
**Pull request by Liam2263**
Sinc is a C# Bot, made with RedUtils.

### CODE REVIEW

**Review by JoshyDevRL — APPROVED** [review]
Looks good 👍

**Comment by tarehart** [comment]
Thanks for offering your bot! Would you be willing to give the source code to one of our moderators so we can do a safety check and then compile ourselves for bot pack purposes?

**Comment by Liam2263** [comment]
Sure, can I send this to you in dms, if not who can I send it to at this time?

**Comment by Liam2263** [comment]
[Sinc(1).zip](https://github.com/RLBot/RLBotPack/files/8765785/Sinc.1.zip)

This is the Sinc zip.

**Comment by Liam2263** [comment]
Alright I sent you the zip and another zip but with the code inside of the folder inside of the zip. Thank you.

**Comment by tarehart** [comment]
Looks good! Can you please allow edits from maintainers (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can add some recompiled binaries?

**Review by tarehart — APPROVED** [review]
Looks good! I've recompiled the binaries and updated the PR. Most of them had no diff, I assume the others were something trivial.

**Pull request merged**
