### PR TITLE
Added TMCP Requirement to Molten

### PR DESCRIPTION
**Pull request by ItsCodeRed**

### CODE REVIEW

**Comment by VirxEC** [comment]
why the virtual environment, it really isn’t needed

**Comment by ItsCodeRed** [comment]
do I just add tmcp to the list of requirements in the txt?

**Comment by VirxEC** [comment]
yeah and the yellow warning triangle will show in the gui

**Comment by ItsCodeRed** [comment]
alright is that better?

**Review by VirxEC — APPROVED** [review]

**Pull request merged**
