### PR TITLE
Bot pack patches

### PR DESCRIPTION
**Pull request by VirxEC**
I've made a global `items.csv` for bots that wish to use it. This is only Nebulous right now but if any bots in the future end up wanting to read it I don't want them all making their own copies in the botpack.

Updated Nebulous to use the global `items.csv`

Also included a few file-path-related fixes:
 - Invisibot (still Windows-only but wasn't working at all)
 - Kamael, Toxic Nexto, and TensorBot on Linux (changed "\\" to "/" in a few places)

### CODE REVIEW

**Comment by tarehart** [comment]
Have you considered making the items data part of the `rlbot` python package instead? Then we could power both the GUI and the bots from the same data, and bots would have a more reliable place to reference the data. Having a bot hard code a relative file path to some location in the bot pack seems brittle to me.

**Comment by VirxEC** [comment]
That is true haha, I’ll look into it

**Comment by Impossibum** [comment]
pretty sure nebulous was grabbing the items.csv files from rlgot gui package to begin with. The included file was only a backup in case someone was running the bot outside of the gui environment.

**Comment by VirxEC** [comment]
@Impossibum The change is actually more for the Rust GUI, where the rlbot gui package will no longer be.

**Comment by VirxEC** [comment]
Done and tested. RLBot/RLBot#594 must be merged and pushed to users before this can be merged.

**Comment by VirxEC** [comment]
Confirmed new Nebulous works with RLBot 1.67.0! This PR is ready to be merged.

**Review by tarehart — APPROVED** [review]

**Pull request merged**
