### PR TITLE
Update ElkBot

### PR DESCRIPTION
**Pull request by rivques**
This should be the last update for a while, hopefully!

### CODE REVIEW

**Comment by VirxEC** [comment]
could you just change `rlbot` to `rlbot==1.*`? my fault, sorry

**Review by tarehart — APPROVED** [review]
That's a lot of changes, nice work!

**Comment by rivques** [comment]
> could you just change `rlbot` to `rlbot==1.*` in `requirements.txt`? my fault, sorry

do i need to do this for my ELP version too?

**Comment by VirxEC** [comment]
nah, this is fine

**Pull request merged**
