### PR TITLE
Add ElkBot to the botpack

### PR DESCRIPTION
**Pull request by rivques**

### CODE REVIEW

**Comment by VirxEC** [comment]
you need to delete your `.git` folder - it's a hidden folder [see this site](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-10-97fbc472-c603-9d90-91d0-1166d1d9f4b5) for how to reveal hidden folders

**Comment by tarehart** [comment]
When I look at the files changed, I see a git submodule rather than bot files. I'm not sure how that happened, but I think that's likely to cause issues with our botpack download script.

**Comment by rivques** [comment]
okay, I'll try again

**Comment by rivques** [comment]
should be ready now

**Comment by VirxEC** [comment]
Great wow, much excitement, awesome looks!

**Review by VirxEC — APPROVED** [review]

**Pull request merged**
