### PR TITLE
PanBot initial commit

### PR DESCRIPTION
**Pull request by John-WL**

### CODE REVIEW

**Comment by robbai** [comment]
Hey,  I noticed your bot is a Java bot, which means it needs to be compiled to be added to the botpack: [Tournament submissions](https://github.com/RLBot/RLBotJavaExample/wiki/Tournament-Submissions).
If you need help with this, just ask in the [Discord](https://discord.gg/zbaAKPt).

**Comment by azeemba** [comment]
I also see multiple `.cfg` files that needs to be trimmed down to be just one config file.

I also wonder if there is any way to trim down the number of files here. If that's data, can it be concatenated to one file?

**Comment by John-WL** [comment]
There are indeed a couple of cfg files that could be compacted to only one single cfg file, and it's a bit of work, but it should definitely be done to reduce project size. I'll focus on that for now, and I'll try to make it autorun afterward.

If you see anything else that needs to be changed, let me know.

Thanks for the quick response guys :)

**Comment by John-WL** [comment]
As for the total number of files, well, it's mostly classes, so I don't think it's trimmable that much? I don't really know, I'm not an expert at trimming classes

**Comment by John-WL** [comment]
Actually, there is this whole PathHandler part that I don't like very much. I want to get rid of that, but it's a lot of work too. There are only like 2 behaviour controllers that use it (dribble and flick), so it's definitely doable.

I think there are some functionnalities in the util section that I don't use and that I could remove too.

**Comment by John-WL** [comment]
And there are some unused classes too actually. I'll update the code once it's trimmed and functionnal again

**Comment by kipje13** [comment]
The botpack is supposed to be plug&play. This means that every bot needs to be compiled before it is added to the botpack. Like Robbie suggested, have a look at [Tournament Submissions](https://github.com/RLBot/RLBotJavaExample/wiki/Tournament-Submissions.). For java bots there should be zero source files.

You can have a look at [Wildfire](https://github.com/John-WL/RLBotPack/tree/master/RLBotPack/Wildfire_Lightfall_Fix) for reference.

**Pull request closed without merging**
