### PR TITLE
Updated VirxEB to COMM-74

### PR DESCRIPTION
**Pull request by VirxEC**
NOTE: Some of the stuff in the changelog might be conflicting. I'm not very smart when it comes to keeping a changelog. In this case, take the word of whatever's lowest on the list.

block_ground_shot will now flip towards the ball
Smarter centers on offense
A majority of the math required to find a shot is now done in C
If VirxEB is already shooting, then the shot tools will only consider up to the shot time
More aggressive defensive play
Removed the retreat loop where it gets pushed to the stack and gets popped right away, and the bot does nothing
VirxEB's general recovery now faces towards the ball
New methods that execute only when VirxEB is in the air and not shooting
Optimized finding a better shot when already shooting
Optimized finding a shot with a cap in the seconds
Added speed corner kickoffs
Searches a lot more slices from the ball prediction
Fixed the defender coming out of the net on an opponent's breakaway
More pathfinding improvements
Smarter backchecks
Retreat works in 2's/1's
More consistent capping of shot times
Fine-tuned shot values (auto calculated on start)
Removed minimum boost requirement (was 24) on aerials
Fixed errors caused by having no teammates
In 2's, if VirxEB is either up down by 2, he will start to play more defensive
More aggressive in 1's (sometimes)
More passive in 1's (sometimes)
Neutral and Offensive playstyles try to keep the ball in the opponent's zone
Linked ball_recovery to recovery
VirxEB can now recover on the ceiling
If VirxEB lands on the ceiling somehow, he can do a ceiling shot
More pathfinding improvements
Pathfinding tries to use less boost and more flips
Jump shots now use flips in their pathfinding
In 4's, 1 VirxEB will patiently wait to try a ceiling shot on the wall xD
Backing checking now considers where the ball will be, instead of where the ball is
Jump shot now auto-calculates the jump threshold
In 2's, if VirxEB is ever down by 2 (or more), he will play more defensively for the rest of the game
Remove units per second requirement in favor of cap/cap_
The height cap on backwards jump shots is now the same as a forwards jump shot
Added double jumps, which is a jump shot but it uses the dodge for extra height
Properly capped shots without a target at 3 seconds
Fixed backwards jump shots
Backwards jump shots no longer have to be within 1/2 the cap/cap_
Bots can now boost in the air via default_throttle
If the ball is getting closer to the net and the bot is behind the ball, it will treat it like the ball is about to go into the net
Cleaned up the code a little bit
Better offensive checks
Each car picks from a list of 10 Octane-preset cars to rock the competition with :P
Defensive bots will face the ball when they're too far off
Instead of replacing shot, shots are updated with new information
Aerials will now be upgraded mid-flight
Aerials can now hit the ball upwards/downwards
Fixed a lot of false positives with pathfinding's rule 1 with tm8's detector
Gravity now gets set after it's been changed in-game. (Via BakkesMod or similar things)
Dumps will now be into the diagonals, allowing for centers
`self.can_shoot` is ignored if (playstyle is Neutral and shot is best_shot or ball_going_in_own_goal)
New, faster, & cleaner methods 'find_shot' and 'find_any_shot'
Aerials with a target now have a default cap of 6
Added the ability for a bot to wait a lot longer for it's shot if it's on offense
New hyper-aggro bot 'ABot'
Smarter `wave_dash` routine
wave_dash is now used in pathfinding (bc it's a lot faster than a flip)

### CODE REVIEW

**Comment by robbai** [comment]
I'm hitting this error when trying to install the package `VirxERLU-CLib`:
```
ERROR: Could not find a version that satisfies the requirement tkinter (from -r C:\Users\wood3\Desktop\RLBotPack\RLBotPack\VirxEB\requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tkinter (from -r C:\Users\wood3\Desktop\RLBotPack\RLBotPack\VirxEB\requirements.txt (line 1))
```

**Comment by tarehart** [comment]
It's my fault sorta, I just created an issue to explain https://github.com/RLBot/RLBot/issues/525

For now it would be good to remove tkinter from requirements.txt, and I'll come up with an alternative soonish.

**Comment by VirxEC** [comment]
Removed 👍

**Comment by VirxEC** [comment]
I would like to do 1 more commit, so don't accept this yet

**Comment by VirxEC** [comment]
That should be good! Pull plz!

**Pull request merged**
