### PR TITLE
Update Noob Bot

### PR DESCRIPTION
**Pull request by rocketeeroof**
mainly removes errors with a few minor changes in behaviour.

### CODE REVIEW

**Comment by VirxEC** [comment]
One more thing, can you please remove these files?

image

They are purely for bot development and only a bot's `/src/` folder is needed in the botpack.

**Comment by VirxEC** [comment]
I know you weren't asked to do this previously but if you could do it now that would be nice - Darx must've missed it when originally approving your pr.

**Comment by rocketeeroof** [comment]
> One more thing, can you please remove these files?
> 
> image
> 
> They are purely for bot development and only the contents of the `/src/` folder is needed in the botpack.

Done

**Review by VirxEC — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
