### PR TITLE
Adding BitBot to the botpack

### PR DESCRIPTION
**Pull request by YOMANSLODOWN**
I have been working on bitbot for quite some time, and I decided it was a good time to share it right before the RlBot Winter Showdown so you guys could try it out.

### CODE REVIEW

**Comment by JoshyDevRL** [comment]
You mind removing that pycache folder in your util folder?

**Comment by YOMANSLODOWN** [comment]
how we looking now?

**Comment by YOMANSLODOWN** [comment]
I also removed OMEN from the botpack. We should be all good now

**Comment by rocketeeroof** [comment]
Looks fine to me.

**Review by VirxEC — APPROVED** [review]

**Pull request merged**
