### PR TITLE
Add Rocket Slayer Bot

### PR DESCRIPTION
**Pull request by John-WL**

### CODE REVIEW

**Comment by John-WL** [comment]
I saw from #64 that adding closed source code might be prohibited. 
This bot is actually open source, so feel free to check the code and add it manually if you prefer:
https://github.com/Flyves/Boss-Battle

**Review by Darxeal — COMMENTED** [review]
I tested it, works great!
However here are some things I noticed:
- the entire bot is almost 60 MB. Half of this are assets, and I suspect you can't do much about it, so that's fine. But do you by any chance know why the main .jar file has to be 31 MB?
- The description could have more information. In the future, I would like a way in the GUI for minigames like these to specify a match config file, so users don't have to set it manually. But for now, could you please add info like mutators, how many bots are supposed to be on each team etc.?
- The github link in the config is not working
- This is optional, but I would recommend adding a `tags = memebot` to the Details section in the config, so your bot shows up in the Special bots tab ;)

**Comment by John-WL** [comment]
- Updated the description. 
- GitHub link should work now. 
- Added `tags = memebot`. 
- The size of the main .jar file seems to be caused by the gradle build process.  
It looks like it takes the pre-compiled classes that contain the animation data, and adds it to the main .jar file (the .sob files in `src/main/resources/car animations/` are actually pre-compiled Java code containing solely animation data). 
So the animation data is actually added _twice_ in the build. 
The pre-compiled classes that contain animation data are loaded at runtime at the moment, so there is no need for them to be included in the main .jar file. 
I've been trying a couple of things in the gradle config file to prevent this for the past 2 hours, without success. 
I tried things like this:
```
sourceSets {
    main {
        java {
            exclude('src/main/resources/car animations/**')
        }
    }
}
```
But, it won't work because it seems like it only prevents un-compiled .java classes from being compiled. 
I'm not sure how to prevent pre-compiled code from being used in the compilation process. 
Any ideas?

**Comment by John-WL** [comment]
After more testing, it seems like in addition to the .sob files, some (if not all the sound files) are being included in the .jar file too.

**Comment by Darxeal** [comment]
I'm no java expert so can't help you much here. Is it maybe possible for the bot to use the assets inside the jar so you can delete the other ones?

**Comment by John-WL** [comment]
The bot uses a sound library that I believe won't permit reading files packed in .jar files easily. 
I replaced the .jar file manually, so the size should be fixed now. 

The process still has to be done manually for now if there are updates in the future, though.

**Review by Darxeal — APPROVED** [review]
Yep that's fine, thank you!

**Pull request merged**
