### PR TITLE
Proposed changes for trimming botpack

### PR DESCRIPTION
**Pull request by ddthj**
#307 

Redox compiled a list of bots that could be removed from the botpack https://github.com/RLBot/RLBotPack/issues/307#issuecomment-1712649487

Of those, we wanted to keep Story Mode bots, Tournament Winners, and other Iconic bots as defined by Fan-favorites, Featured on youtube, and unique playstyles.

Here are my removals based on the above criteria:
50-50 minigame
Airball / Airball bot
Aether
Atlas (won winter invitational)
BitBot
Caster Bot
CheeseBot Family
Zero-G
DisasterBot
Elkbot
Engine
Formularbot
Isopod_for_botpack
JoeyBot
KickoffOnly
L0laapk3_shared
Levi
MirrorBot
Om_Nom
Omus
Oneborg
PacificScienceScratcher
Puffy
quantum-league
RandomStandard
Rocketnoodles
Seer (Because it is not the tournament version)
SideSwipe
SignificanceBar
Slime
snowbot
SSL_of_GS
Tankar
TensorBot
The Forsaken
tron
TwitchInteraction
Typeracer
Vector
Virxeb (already removed from this branch)

### CODE REVIEW

**Comment by VirxEC** [comment]
Puffy if I do recall did win the spike rush tournament, might want to keep him

**Comment by ddthj** [comment]
I thought about that. Should those smaller tournaments really count though? Not many people even know about spike rush.

**Comment by redd-rl** [comment]
I feel like it should still stick, some people might want to play Extra Mode bots, I figure?

**Comment by ddthj** [comment]
Sure

**Comment by NicEastvillage** [comment]
I am sad to see Typerracer and tron and quantum-league being removed, but it makes sense if we want to streamline the bot pack. They should definitely make a comeback in a meme pack eventually.

**Review by TheBlocks — CHANGES_REQUESTED** [review]
As per Lola's comment (https://github.com/RLBot/RLBotPack/issues/307#issuecomment-1715354539), we shouldn't remove l0laapk3_shared/rlutilities since his bots depend on it.

**Review by TheBlocks — CHANGES_REQUESTED** [review]
We shouldn't remove Atlas because it's present in easy Story Mode.

**Pull request closed without merging**
