### PR TITLE
Updating Sinc and fixing a possibly faulty RedUtils in Sinc

### PR DESCRIPTION
**Pull request by Liam2263**
Changed Sinc 2s and improved it.
Main reason I am sending this pr though is because of a issue with the Arrive function in the RedUtils that is fixed in this new version.
Oh and Sinc had a very random and weird bug which Sinc will go across the field and go to this one weird small pad on the opponents field, which is fixed as well.
Sorry for sending a pr soon after it was added but this will be one of the last updates for Sinc going forwards.

- SoldierDoge (the one and only)
- (Btw I am willing to give collab access on the fork as well as give any zips you need through discord dms)

### CODE REVIEW

**Review by JoshyDevRL — APPROVED** [review]

**Comment by JoshyDevRL** [comment]
Looks good, for any github mods that are peeking here 👀

**Comment by VirxEC** [comment]
You appear to include many source files and project files that might be required to build the bot but aren't required to run the bot. Distributing such source files for others to look at is what a GitHub repo is for. Please remove as many unneeded files as possible, and don't forget to test your changes!

**Comment by Liam2263** [comment]
Hello! Sorry about that, I have deleted what I believe to be the only non-needed item in the bot. It should be good now, sorry about that.

**Comment by VirxEC** [comment]
Looks good to me, I think @tarehart might want to look at this though because it is a compiled bot.

**Comment by Liam2263** [comment]
Alright! I do have the Sinc that’s not compiled if you would like to see it.

**Review by tarehart — APPROVED** [review]

**Pull request merged**
