### PR TITLE
Update CheeseBot + Add Cheesus

### PR DESCRIPTION
**Pull request by JoshyDevRL**

### CODE REVIEW

**Comment by VirxEC** [comment]
can you please delete the pycache folders?

**Comment by JoshyDevRL** [comment]
Ok, done forgot to del them for cheesebot

**Comment by VirxEC** [comment]
also you're including all your source files - only the compiled files are needed for running the bot

**Comment by JoshyDevRL** [comment]
oooh yea mb

**Comment by Darxeal** [comment]
Virx beat me to it, but checkout https://github.com/RLBot/RLBotCSharpExample/wiki/Tournament-Submissions

**Comment by JoshyDevRL** [comment]
hm ok, this should do it

**Comment by VirxEC** [comment]
you still have all the source code for RedUtils

**Comment by VirxEC** [comment]
and debug binaries (you only need release-built binaries)

**Comment by JoshyDevRL** [comment]
which files? im stupid

**Comment by JoshyDevRL** [comment]
this should work

**Comment by VirxEC** [comment]
Looks good to me, I assume you tested it and it launched? If it did, we'll merge.

**Comment by JoshyDevRL** [comment]
yea i tested it

**Comment by VirxEC** [comment]
One second - `RLBotPack/Cheesus/Bot.runtimeconfig.dev.json` has absolute paths that will only work on your system. If you just delete the file, will the bot still work?

**Comment by JoshyDevRL** [comment]
yea it works, but i think i saw that same file with abs path in redbots file maybe take a look?

**Comment by VirxEC** [comment]
Unfortunately, yes, there is. I didn't approve that pr tho :/

**Review by VirxEC — APPROVED** [review]

**Pull request merged**
