### PR TITLE
Added Isopod

### PR DESCRIPTION
**Pull request by Zingothy**
yes

### CODE REVIEW

**Comment by JoshyDevRL** [comment]
Are you intentionally adding both **oldbot.py** and **bot.py**?

**Comment by JoshyDevRL** [comment]
Sounds good! 🧀 _Joshy Approved_

**Comment by NicEastvillage** [comment]
Please add relevant tags in the `.cfg` files so it appears in the relevant tabs in the gui. You can find the categories here https://github.com/RLBot/RLBotGUI/blob/master/rlbot_gui/gui/js/categories.js

**Comment by Zingothy** [comment]
.cfg should be updated now

**Review by NicEastvillage — APPROVED** [review]

**Pull request merged**
