### PR TITLE
Add Slime Bot

### PR DESCRIPTION
**Pull request by Zingothy**
Scratch bot made by Zing

### CODE REVIEW

**Comment by rocketeeroof** [comment]
I'm not a moderator but i noticed two things:
1. The "Slime" file outside the inner RLBotPack file could probably be deleted, since that's not where the bots are stored
2. You can remove any __pycache__ folders without consequence

Here's how to delete a file on GitHub:
Open the file you want to delete
Click the button with "..."
"Remove Directory"
in the bottom of the page, "commit to master"

**Comment by VirxEC** [comment]
Also the only folder that's needed is `RLBotPack/Slime/Slime` and all add contents outside of that can be safely deleted

**Comment by rocketeeroof** [comment]
Considering the changes, looks good to me, i guess we'll wait for an official to check it out.

**Comment by JoshyDevRL** [comment]
It seems that there are still some useless files in the Slime directory, it seems that your fork is not up-to-date anymore.

**Comment by Zingothy** [comment]
which files should I get rid of?

**Comment by VirxEC** [comment]
`run.py`, `run.bat`, `rlbot.cfg`, and `RefreshEnv.cmd` can all be removed safely

**Review by VirxEC — APPROVED** [review]
Congrats on making your first bot!

**Pull request merged**
