### PR TITLE
Om Nom Scratch Bot Pack Submission

### PR DESCRIPTION
**Pull request by FootlessQuill54**

### CODE REVIEW

**Review by tarehart — COMMENTED** [review]
I agree with Virx that you can get rid of the desktop.ini and the backup sb3 file. Looks good besides that!

**Comment by VirxEC** [comment]
🥴 You need to delete the files

**Comment by VirxEC** [comment]
Looks good! Do you agree, @tarehart ?

**Review by tarehart — APPROVED** [review]
Yes I agree, looks good!

**Pull request merged**
